Algoritmo "Idades"


Var

   nome1, nome2 : caractere
   idade1, idade2 : inteiro
   media : real
   

Inicio

   escreva ("Digite o nome da primeira pessoa: ")
   leia (nome1)
   escreva ("Informe a idade dessa pessoa: ")
   leia (idade1)
   escreva ("Digite o nome da segunda pessoa: ")
   leia (nome2)
   escreva ("Informe a idade dessa pessoa: ")
   leia (idade2)
   
   media <- (idade1 + idade2) / 2
   
   escreva ("A idade média de ", nome1, " e ", nome2, " é de ", media:5:1)


Fimalgoritmo