Algoritmo "medidas"

Var

 A, B, C, AreaQ, AreaR, AreaT : real


Inicio

 escreva("Informe a medida de A: ")
 leia(A)
 escreva("Informe a medida de B: ")
 leia(B)
 escreva("Informe a medida de C: ")
 leia(C)
 
 AreaQ <- exp(A, 2.0)
 AreaR <- a * b
 AreaT <- (a * b) / 2
 
 escreval("Area do quadrado: ", AreaQ:8:4)
 escreval("Area do retângulo: ", AreaR:8:4)
 escreval("Area do triângulo: ", AreaT:8:4)


Fimalgoritmo